--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ErikPDev/AdvanceDeaths
build-by-default: true
branches:
- master
projects:
  AdvanceDeaths:
    path: ""
    icon: "resources/icon.png"
...
