--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ErikPDev/AdvanceDeaths
build-by-default: true
branches:
  - master
projects:
  AdvanceDeaths:
    path: ""
    icon: "assets/icon.png"
    lint:
      phpstan: true
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.0.1
...