name: AdvanceDeaths
author: ErikPDev
api: 3.20.0
version: 2.0
main: ErikPDev\AdvanceDeaths\Main
mcpe-protocol: [440, 449, 465] # More protocols are supported but I don't know how to get the id. Make a pull request if you know =D
virions:
  - libasynql