name: AdvanceDeaths
author: ErikPDev
api: 3.20.0
version: 3.0
main: ErikPDev\AdvanceDeaths\Main
# mcpe-protocol: [440, 449, 465, 471] # More protocols are supported but I don't know how to get the id. Make a pull request if you know =D, Removed this :p
softdepend:
  - EconomyAPI
  - ScoreHud

commands:
  advancedeaths:
    description: "See a player stat!"
    permission: "advancedeaths.use"
  ads:
    description: "See a player stat!"
    permission: "advancedeaths.use"
  rconAdvanceDeathsManager:
    description: "Get the top leaderboard. Implemented for RCON"
    permission: "advancedeaths.rcon"


permissions:
  advancedeaths.use:
    description: "Permission to use the AdvanceDeaths commands."
    default: true
  advancedeaths.rcon:
    description: "Permission to use the AdvanceDeaths rcon commands."
    default: op
