---
name: AdvanceDeaths
version: 0.0.1
main: ErikPDev\AdvanceDeaths\ADMain
src-namespace-prefix: ErikPDev\AdvanceDeaths
api: 4.0.0
softdepend:
  - "DiscordBot"
  - "EconomyAPI"
  - "Capital"
permissions:
  advancedeaths.use:
    description: "Permission to use the AdvanceDeaths commands."
    default: true
...
