---
name: AdvanceDeaths
version: 4.1.0
main: ErikPDev\AdvanceDeaths\ADMain
api: 5.0.0
softdepend:
  - "BedrockEconomy"
permissions:
  advancedeaths.use:
    description: "Permission to use the AdvanceDeaths commands."
    default: true
...
