---
name: AdvanceDeaths
version: 4.0.2
main: ErikPDev\AdvanceDeaths\ADMain
api: 4.0.0
softdepend:
  - "DiscordBot"
  - "EconomyAPI"
  - "BedrockEconomy"
  - "ScoreHud"
permissions:
  advancedeaths.use:
    description: "Permission to use the AdvanceDeaths commands."
    default: true
...
